version: '3.7'
services:
  
  play-with-docker:
    container_name: play-with-docker
    image: docker/getting-started:pwd
    ports:
      - 8080:80

  adventure-works-db-sql-server:
    image: stvansolano/adventure-works:latest
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  dotnet-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
    - "80:80"
    environment:
      -  ASPNETCORE_URLS=http://+:80
  
  #dotnet-backend:
  #  build:
  #    context: .
  #    dockerfile: material/ProductsApi/Dockerfile
  #  ports:
  #  - "6001:5000"
  #  links:
  #  - adventure-works-db-sql-server
  #  depends_on:
  #  - adventure-works-db-sql-server

# docker-compose up -d
